function getRandomImage() {
    //declare an array to store the images
    var randomImage = new Array();

    //insert the URL of images in array
    randomImage[0] = "amadeus.png";
    randomImage[1] = "ronaldkyle.jpg";
    randomImage[2] = "gregory.jpeg";


    //generate a number and provide to the image to generate randomly
    var number = Math.floor(Math.random() * randomImage.length);



    //return the images generated by a random number
    return document.getElementById("imgResult").innerHTML = '<img src="' + randomImage[number] + '" />';;
}
function PlaySound() {
    var sound = new Audio();
    sound.src = "sound1.ogg";
    document.getElementById(sound);
    sound.play();
}